image: harbor.uni-muenster.de/proxy-docker/openapitools/openapi-generator-cli:v7.17.0

variables:
  NPM_PREFIX: "@scdhapis"
  ARTIFACT_DIR: out


.release_rules_tag:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/ # describe how your version tags look like!

.prerelease_rules_tag:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-rc/ # describe how your pre-release tags look like!


.spec_matrix: &spec_matrix
  parallel:
    matrix:
      - SPEC:
          - dts-openapi.yaml
          - static-collection-openapi.yaml
          - facade-openapi.yaml
      
stages:
  - test
  - generate
  - build
  - deploy

validate:
  stage: test
  <<: *spec_matrix
  script:
    - openapi-generator-cli validate -i $SPEC

generate:
  stage: generate
  before_script:
    - apt-get -y install sed
  script:
    - oagen/fix-paths.sed --in-place oagen/*.yaml
    - openapi-generator-cli batch oagen/*.yaml
    - ls -l $ARTIFACT_DIR
  artifacts:
    paths:
      - $ARTIFACT_DIR
    expire_in: 1 hour


build-typescript-axios:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: build
  needs:
    - generate
  script:
    - cd $ARTIFACT_DIR/typescript-axios
    - npm i
    - npm run build
  artifacts:
    paths:
      - $ARTIFACT_DIR/typescript-axios
    expire_in: 1 hour

deploy-typescript-axios:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: deploy
  needs:
    - build-typescript-axios
  script:
    - cd $ARTIFACT_DIR/typescript-axios
    - echo "${NPM_PREFIX}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - npm publish
  rules:
    - !reference [ .release_rules_tag, rules ]

# the pre-release is tagged "next"
deploy-prerelease-typescript-axios:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: deploy
  needs:
    - build-typescript-axios
  script:
    - cd $ARTIFACT_DIR/typescript-axios
    - echo "${NPM_PREFIX}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - npm publish --tag next
  rules:
    - !reference [ .prerelease_rules_tag, rules ]


build-typescript-fetch:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: build
  needs:
    - generate
  script:
    - cd $ARTIFACT_DIR/typescript-fetch
    - npm i
    - npm run build
  artifacts:
    paths:
      - $ARTIFACT_DIR/typescript-fetch
    expire_in: 1 hour

deploy-typescript-fetch:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: deploy
  needs:
    - build-typescript-fetch
  script:
    - cd $ARTIFACT_DIR/typescript-fetch
    - echo "${NPM_PREFIX}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - npm publish
  rules:
    - !reference [ .release_rules_tag, rules ]

# the pre-release is tagged "next"
deploy-prerelease-typescript-fetch:
  image: harbor.uni-muenster.de/proxy-docker/library/node:latest
  stage: deploy
  needs:
    - build-typescript-fetch
  script:
    - cd $ARTIFACT_DIR/typescript-fetch
    - echo "${NPM_PREFIX}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - npm publish --tag next
  rules:
    - !reference [ .prerelease_rules_tag, rules ]



generic-package:
  image: harbor.uni-muenster.de/proxy-docker/library/debian:stable-slim
  stage: deploy
  before_script:
    - apt-get -y update
    - apt-get -y install curl zip
  script:
    - zip ${CI_PROJECT_NAMESPACE_SLUG}-${CI_COMMIT_TAG}.zip *.yaml schemas/* params/*
    - |
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
        --upload-file ${CI_PROJECT_NAMESPACE_SLUG}-${CI_COMMIT_TAG}.zip \
        ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAMESPACE_SLUG}/${CI_COMMIT_TAG}/${CI_PROJECT_NAMESPACE_SLUG}-${CI_COMMIT_TAG}.zip
  rules:
    - !reference [ .prerelease_rules_tag, rules ]
    - !reference [ .release_rules_tag, rules ]

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_MESSAGE'
    assets:
      links:
        - name: ${CI_PROJECT_NAMESPACE_SLUG}-${CI_COMMIT_TAG}.zip
          url: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAMESPACE_SLUG}/${CI_COMMIT_TAG}/${CI_PROJECT_NAMESPACE_SLUG}-${CI_COMMIT_TAG}.zip
  rules:
    - !reference [ .prerelease_rules_tag, rules ]
    - !reference [ .release_rules_tag, rules ]


pages:
  pages: true
  stage: deploy
  image: harbor.uni-muenster.de/proxy-docker/library/busybox
  script:
    - mkdir -p public
    - cp --recursive examples public/
