openapi: 3.1.0
info:
  title: DTS
  description: All DTS endpoints
  version: 1.0rc1

# USE INTERNED SPEC FROM DIRECTORY internal INSTEAD!

paths:

  /entry:
    get:
      operationId: entry
      summary: GET request on the entry endpoint of the DTS API
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/EntryOK'
        "5XX":
          description: Unexpected error

  /collection/{id}/{page}/{nav}.json:
    get:
      operationId: collection
      summary: The collection endpoint is used for navigating collections. A collection contains metadata for the collection itself and an array of members. Each member is either a Collection or a Resource.
      parameters:
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Id'
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Page'
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Nav'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/NavigationOK'

  /navigation:
    get:
      operationId: navigation
      summary: GET request on the navigation endpoint of the DTS API
      parameters:
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/ResourceQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/RefQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/StartQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/EndQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/DownQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/TreeQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/PageQ'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/NavigationOK'
        "5XX":
          description: Unexpected error

  /document:
    get:
      operationId: document
      summary: The collection endpoint is used for navigating collections. A collection contains metadata for the collection itself and an array of members. Each member is either a Collection or a Resource.
      parameters:
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/ResourceQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/RefQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/StartQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/EndQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/TreeQ'
        - $ref: 'components/document-query-params.yaml#/components/parameters/MediaTypeQ'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/DocumentOK'
        "5XX":
          description: Unexpected error

