openapi: 3.1.0
info:
  title: DTS Facade
  description: Collection, Navigation, and Document endpoints on a stateless microservice
  version: 1.0rc1


paths:
  /{provider}/{location}/entry:
    get:
      operationId: entry
      tags:
        - entry
      summary: GET request for the DTS entry endpoint.
      description: The DTS entry endpoint is a service registry with follow up links to other services.
      parameters:
        - $ref: '#/components/parameters/Provider'
        - $ref: '#/components/parameters/Location'
      responses:
        "200":
          $ref: "components/responses.yaml#/components/responses/EntryOK"
        "400":
          $ref: 'components/responses.yaml#/components/responses/LODBadRequest'
        "404":
          $ref: 'components/responses.yaml#/components/responses/LODNotFound'
        "5XX":
          description: Unexpected error
  /{provider}/{location}/collection/:
    get:
      operationId: collectionDefault
      tags:
        - collection
      summary: GET request for the default collection on the collection endpoint of the DTS API.
      description: The collection endpoint is used for navigating collections. This path returns the default collection.
      parameters:
        - $ref: '#/components/parameters/Provider'
        - $ref: '#/components/parameters/Location'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/CollectionOK'
        "400":
          $ref: 'components/responses.yaml#/components/responses/LODBadRequest'
        "404":
          $ref: 'components/responses.yaml#/components/responses/LODNotFound'
        "5XX":
          description: Unexpected error

  /{provider}/{location}/collection/{id}:
    get:
      operationId: collection
      tags:
        - collection
      summary: GET request on the collection endpoint of the DTS API.
      description: The collection endpoint is used for navigating collections. A collection contains metadata for the collection itself and an array of members. Each member is either a Collection or a Resource.
      parameters:
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Id'
        - $ref: 'components/collection-query-params.yaml#/components/parameters/NavQ'
        - $ref: 'components/collection-query-params.yaml#/components/parameters/PageQ'
        - $ref: '#/components/parameters/Provider'
        - $ref: '#/components/parameters/Location'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/CollectionOK'
        "400":
          $ref: 'components/responses.yaml#/components/responses/LODBadRequest'
        "404":
          $ref: 'components/responses.yaml#/components/responses/LODNotFound'
        "5XX":
          description: Unexpected error

  /{provider}/{location}/navigation/{resource}:
    get:
      operationId: navigation
      tags:
        - navigation
      summary: GET request on the navigation endpoint of the DTS API.
      description: In addition to the DTS specs this requires the path parameter 'collection', which can easily be passed around with the URI templates.
      parameters:
        - $ref: 'components/navigation-path-params.yaml#/components/parameters/Resource'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/RefQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/StartQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/EndQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/DownQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/TreeQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/PageQ'
        - $ref: '#/components/parameters/Provider'
        - $ref: '#/components/parameters/Location'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/NavigationOK'
        "400":
          $ref: 'components/responses.yaml#/components/responses/LODBadRequest'
        "404":
          $ref: 'components/responses.yaml#/components/responses/LODNotFound'
        "5XX":
          description: Unexpected error

  /{provider}/{location}/document/{resource}:
    get:
      operationId: document
      tags:
        - document
      summary: GET request on the document endpoint of the DTS API.
      description: The Document endpoint is used to access the content of document, as opposed to metadata (which is found in collections).
      parameters:
        - $ref: 'components/navigation-path-params.yaml#/components/parameters/Resource'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/RefQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/StartQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/EndQ'
        - $ref: 'components/navigation-query-params.yaml#/components/parameters/TreeQ'
        - $ref: 'components/document-query-params.yaml#/components/parameters/MediaTypeQ'
        - $ref: '#/components/parameters/Provider'
        - $ref: '#/components/parameters/Location'
      responses:
        "200":
          $ref: 'components/responses.yaml#/components/responses/DocumentOK'
        "400":
          $ref: 'components/responses.yaml#/components/responses/BadRequest'
        "404":
          $ref: 'components/responses.yaml#/components/responses/NotFound'
        "5XX":
          description: Unexpected error

# Used components must be imported here!
components:
  parameters:
    Provider:
      name: provider
      description: The type of content provider suitable for accessing the location.
      in: path
      required: true
      schema:
        type: string
        format: uri
    Location:
      name: location
      description: The base location of the project resources. This can be a DOI, an URL etc.
      in: path
      required: true
      schema:
        type: string
        format: uri
