openapi: 3.1.0
info:
  title: DTS
  description: Entry and Collection endpoints
  version: 1.0rc1


paths:
  /entry:
    $ref: "./paths/entry.yaml"

  /collection/{id}/{page}/{nav}.json:
    $ref: "./paths/collection-path.yaml"
