openapi: 3.1.0
info:
  title: DTS
  description: Entry and Collection endpoints
  version: 1.0rc1


paths:
  /entry:
    get:
      operationId: entry
      summary: GET request on the entry endpoint of the DTS API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        "5XX":
          description: Unexpected error

  /collection/{id}/{page}/{nav}.json:
    get:
      operationId: collection
      summary: The collection endpoint is used for navigating collections. A collection contains metadata for the collection itself and an array of members. Each member is either a Collection or a Resource.
      parameters:
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Id'
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Page'
        - $ref: 'components/collection-path-params.yaml#/components/parameters/Nav'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'

# Used components must be imported here!
components:
  schemas:
    Any:
      $ref: 'components/any.yaml#/components/schemas/Any'
    CitableUnit:
      $ref: 'components/citableUnit.yaml#/components/schemas/CitableUnit'
    CitationTree:
      $ref: 'components/citationTree.yaml#/components/schemas/CitationTree'
    CiteStructure:
      $ref: 'components/citationTree.yaml#/components/schemas/CiteStructure'
    Collection:
      $ref: 'components/collection.yaml#/components/schemas/Collection'
    LODContext:
      $ref: 'components/context.yaml#/components/schemas/LODContext'
    ContextUri:
      $ref: 'components/context.yaml#/components/schemas/ContextUri'
    ContextObject:
      $ref: 'components/context.yaml#/components/schemas/ContextObject'
    ContextArray:
      $ref: 'components/context.yaml#/components/schemas/ContextArray'
    Download:
      $ref: 'components/download.yaml#/components/schemas/Download'
    dublinCore:
      $ref: 'components/dublinCore.yaml#/components/schemas/DublinCore'
    Entry:
      $ref: 'components/entry.yaml#/components/schemas/Entry'
    Id:
      $ref: 'components/id.yaml#/components/schemas/Id'
    Pagination:
      $ref: 'components/pagination.yaml#/components/schemas/Pagination'

      
